* Mu4e-crypto
This package provides utilities that simplify encrypting or decrypting emails for mu4e, instead of manually switching to your termial then running the GnuPG with tedious and repetitive arguments.
** Installation
#+BEGIN_SRC
(load "/your/path/to/package")
(define-key mu4e-compose-mode-map (kbd "C-c C-m e") 'mu4e-crypto--encrypt-message)
(define-key mu4e-view-mode-map (kbd "C-c C-m d") 'mu4e-crypto--decrypt-message)
#+END_SRC
** Copying
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
